project_id = "iaenzywwyiaccnnpdqzt"

[functions.ai-stage-room]
verify_jwt = true

[functions.ai-material-swap]
verify_jwt = true

[functions.process-list-upload]
verify_jwt = true

[functions.ai-deal-suggestions]
verify_jwt = true

[functions.ai-inbox-analysis]
verify_jwt = true

[functions.generate-buyer-message]
verify_jwt = true

[functions.dialer-copilot]
verify_jwt = true

[functions.ai-website-writer]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.ai-property-analysis]
verify_jwt = true

[functions.vapi-webhook]
verify_jwt = false

[functions.vapi-create-assistant]
verify_jwt = true

[functions.speed-to-lead]
verify_jwt = false
