project_id = "iaenzywwyiaccnnpdqzt"

[functions.ai-stage-room]
verify_jwt = false

[functions.ai-material-swap]
verify_jwt = false

[functions.process-list-upload]
verify_jwt = false

[functions.ai-deal-suggestions]
verify_jwt = false

[functions.ai-inbox-analysis]
verify_jwt = false

[functions.generate-buyer-message]
verify_jwt = false

[functions.dialer-copilot]
verify_jwt = false

[functions.ai-website-writer]
verify_jwt = false
