import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version',
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: corsHeaders });

  try {
    const sb = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    );

    // Support manual trigger with specific buy_box_id or run all active
    let buyBoxFilter: any = { is_active: true };
    try {
      const body = await req.json();
      if (body?.buy_box_id) {
        buyBoxFilter = { id: body.buy_box_id };
      }
    } catch { /* no body = run all */ }

    const { data: buyBoxes, error: bbError } = await sb
      .from('buy_boxes')
      .select('*, organizations(automation_mode)')
      .match(buyBoxFilter);

    if (bbError) throw bbError;

    let queued = 0;
    const results: any[] = [];

    for (const bb of buyBoxes ?? []) {
      const criteria = (bb.criteria as any) || {};
      
      // Find properties matching this buy box that haven't been offered yet
      let query = sb
        .from('properties')
        .select('id, address, city, state, zip, arv, repair_estimate, mao_standard, owner_phone, owner_email, owner_name, property_type, beds, asking_price')
        .eq('user_id', bb.user_id)
        .in('status', ['new', 'contacted', 'follow_up'])
        .is('offer_sent_at', null);

      if (criteria.price_max) query = query.lte('asking_price', criteria.price_max);
      if (criteria.price_min) query = query.gte('asking_price', criteria.price_min);
      if (criteria.property_types?.length) {
        query = query.in('property_type', criteria.property_types);
      }
      if (criteria.min_beds) query = query.gte('beds', criteria.min_beds);

      const { data: matches } = await query.limit(bb.max_daily_offers || 10);

      for (const prop of matches ?? []) {
        const arv = prop.arv ?? prop.asking_price ?? 0;
        const repairs = prop.repair_estimate ?? 0;
        const pct = bb.offer_percentage ?? criteria.offer_pct ?? 0.70;
        const offerAmount = Math.round(arv * pct - repairs);
        if (offerAmount <= 0) continue;

        const mode = (bb.organizations as any)?.automation_mode ?? 'hybrid';

        // Create offer record
        const { data: offer, error: offerErr } = await sb.from('offers').insert({
          property_id: prop.id,
          user_id: bb.user_id,
          organization_id: bb.organization_id,
          amount: offerAmount,
          status: mode === 'full_auto' ? 'pending_send' : 'pending_approval',
          contact_phone: prop.owner_phone,
          contact_email: prop.owner_email,
          source: 'auto_engine',
          notes: `Auto-generated by buy box "${bb.name}" | ARV: $${arv.toLocaleString()} × ${(pct * 100).toFixed(0)}% - Repairs: $${repairs.toLocaleString()}`,
        }).select('id').single();

        if (!offerErr && offer) {
          queued++;
          results.push({
            property: prop.address,
            offer_amount: offerAmount,
            status: mode === 'full_auto' ? 'pending_send' : 'pending_approval',
          });
        }
      }

      // Update buy box stats
      await sb.from('buy_boxes').update({
        last_run_at: new Date().toISOString(),
        total_offers_sent: (bb.total_offers_sent || 0) + queued,
        updated_at: new Date().toISOString(),
      }).eq('id', bb.id);
    }

    return new Response(
      JSON.stringify({ success: true, queued, results }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error) {
    console.error('Auto-offer engine error:', error);
    return new Response(
      JSON.stringify({ success: false, error: error instanceof Error ? error.message : 'Unknown error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
